language: python
install:
- pip install pygments
- pip install mkdocs
- pip install mkdocs-material
- pip install pymdown-extensions
script:
- mkdocs build --verbose --clean #--strict
deploy:
 provider: pages
 repo: DFiantHDL/DFiantHDL.github.io
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 target_branch: master
 on:
   branch: master