# Project information
site_name: DFiant HDL (DFHDL)
site_dir: site
site_url: https://dfianthdl.github.io/
site_description: DFiant Hardware Description Language (DFHDL) Documentation
site_author: Oron Port

# Repository
repo_name: 'DFiantHDL/DFHDL'
repo_url: 'https://github.com/DFiantHDL/DFHDL'

# Copyright
copyright: Copyright &copy; 2021 <a href="https://www.dfiant.works">DFiant Inc.</a>

# Configuration
theme:
    logo: images/DF-logo-dark.png
    name: 'material'
    palette:
      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    font:
        text: 'Roboto'
        code: 'Roboto Mono'    
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        # - navigation.instant
    icon:
        logo: 'material/home'    
        
# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://www.github.com/DFiantWorks/'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/company/dfiant'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/DFiantWorks'
        

nav:
  - Home: index.md
  - Introduction:
    # - DFDocs: index.md
    # - 'DFHDL: First Look': intro/first-look/index.md
    - Technology: intro/technology/index.md
  - Getting Started:
    - Initial Setup: getting-started/initial-setup/index.md
    - Hello Hardware World: getting-started/hello-world/index.md
  - Run In Browser: 
    - 1-Bit Full Adder: in-browser/1-bit-full-adder/index.md
    - N-Bit Full Adder: in-browser/n-bit-full-adder/index.md
    - Counter: in-browser/counter/index.md
    - LED Blinker: in-browser/led-blinker/index.md
    # - LFSR: in-browser/lfsr/index.md
    - ALU: in-browser/alu/index.md
    - UART Transmitter: in-browser/uart-tx/index.md
  # - User Guide:
  #   - Domain Abstractions: user-guide/design-domains/index.md
  #   - Designs & Hierarchies: user-guide/designs/index.md
  #   - Type System: user-guide/type-system/index.md
  #   - Functions/Methods: user-guide/methods/index.md
  #   - Connectivity: user-guide/connectivity/index.md
  #   - State/Registers/Memory: user-guide/state/index.md
  #   - Conditionals: user-guide/conditionals/index.md
  #   - Processes: user-guide/processes/index.md
  #   - Interfaces [WIP]: user-guide/interfaces/index.md
  #   - Domains [WIP]: user-guide/domains/index.md
  #   - Scopes [WIP]: user-guide/scopes/index.md
  #   - Naming: user-guide/naming/index.md
  #   - Meta Hardware Description: user-guide/meta/index.md
  #   - Compilation: user-guide/compilation/index.md
  #   - Simulation: user-guide/simulation/index.md
  #   - Synthesis: user-guide/synthesis/index.md
  #   - Errors: user-guide/errors/index.md
  # - Transitioning:
  #   - From Verilog: transitioning/from-verilog/index.md
    # - From VHDL: transitioning/from-vhdl/index.md
  - About:
    # - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/LICENSE.md
    - Acknowledgements: about/acknowledgements.md

markdown_extensions:
    - toc:
        # https://github.com/squidfunk/mkdocs-material/discussions/3535
        permalink: ''
    - abbr
    - attr_list  
    - md_in_html  
    - admonition
    - pymdownx.blocks.html
    - pymdownx.snippets:
        check_paths: true
        auto_append:
          - docs/include/abbr.md
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences:
        custom_fences:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.fence_mathjax_format    
          - name: scastie
            class: scastie
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.details
    - pymdownx.inlinehilite: 
        custom_inline:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
    - pymdownx.highlight:
        use_pygments: true
        linenums_style: pymdownx.inline
        linenums: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://scastie.scala-lang.org/embedded.js
  - javascripts/scastie.js
  - javascripts/d3.js
  - javascripts/elk.bundled.js
  - javascripts/d3-hwschematic.js
  - javascripts/d3-hwschematic-embed.js

extra_css:
  - css/scastie.css
  - css/vs.css
  - css/lhs-permalink.css
  - css/dfhdl-admonition.css
  - css/rtl-admonition.css
  - css/d2.css
  - css/schemdraw.css
  - css/operation-tables.css
  - css/d3-hwschematic.css

hooks:
  - docs/include/schemdraw_hook.py
  - docs/include/scastie_hook.py

plugins:
  - search
  - autorefs
  - d2
  # - glightbox
  - redirects:
      redirect_maps:
          'LEGaTO/index.md': 'index.md'

