# Project information
site_name: DFDocs
site_dir: site
site_url: https://dfianthdl.github.io/
site_description: DFiant Hardware Description Language (HDL) Documentation
site_author: Oron Port

# Repository
repo_name: 'DFiantHDL/DFiant'
repo_url: 'https://github.com/DFiantHDL/DFiant'

# Copyright
copyright: Copyright &copy; 2019 <a href="https://www.researchgate.net/profile/Oron_Port">Oron Port</a> and <a href="https://yoav.net.technion.ac.il">Yoav Etsion</a>

# Configuration
theme:
    name: 'material'
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'    
    features:
        - tabs
        - instant
    icon:
        logo: 'material/home'    
        
# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://www.github.com/soronpo/'
    - icon: fontawesome/brands/researchgate
      link: 'https://www.researchgate.net/profile/Oron_Port'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/soronpo'
        

nav:
  - Introduction:
    - DFDocs: index.md
    - 'DFiant: First Look': intro/first-look/index.md
    - Motivation (Why Another HDL): intro/motivation/index.md
    - A Dataflow Hardware Description Abstraction: intro/dataflow-abstraction/index.md
  - Getting Started:
    - Initial Setup: getting-started/initial-setup/index.md
    - Hello Hardware World: getting-started/hello-world.md
  - User Guide:
    - Type System: user-guide/type-system/index.md
    - State (Memory): user-guide/state/index.md
    - Connectivity: user-guide/connectivity/index.md
    - Meta Hardware Description: user-guide/meta/index.md
    - Compilation: user-guide/compilation/index.md
    - Simulation: user-guide/simulation/index.md
    - Synthesis: user-guide/synthesis/index.md
    - Errors: user-guide/errors/index.md
  - About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/LICENSE.md
    - Acknowledgements: about/acknowledgements.md

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - 'https://embed.scalafiddle.io/integration.js'

markdown_extensions:
    - toc:
        # See https://github.com/facelessuser/pymdown-extensions/issues/609
        permalink: "\ue157"
    - admonition
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.inlinehilite 
    - pymdownx.highlight:
        use_pygments: true
        linenums_style: pymdownx.inline
        linenums: true
      
extra_css:
    - css/vs.css
    - css/extra.css


plugins:
    - search
    - redirects:
        redirect_maps:
            'LEGaTO/index.md': 'index.md'

