site_name: DFDocs
site_url: https://dfianthdl.github.io/
site_description: DFiant Hardware Description Language (HDL) Documentation
site_author: Oron Port

repo_url: https://github.com/DFiantHDL

theme:
    name: mkdocs
    highlightjs: true
    hljs_style: googlecode
    hljs_languages:
        - scala
        - vhdl
        - verilog

nav:
    - Introduction:
        - 'DFiant: First Look': intro/first-look/index.md
        - Motivation (Why Another HDL): intro/motivation/index.md
        - A Dataflow Hardware Description Abstraction: intro/dataflow-abstraction/index.md
    - Getting Started:
        - Initial Setup: getting-started/initial-setup/index.md
        - Hello Hardware World: getting-started/hello-world.md
    - User Guide:
        - Type System: user-guide/type-system/index.md
        - Connectivity: user-guide/connectivity/index.md
        - State: user-guide/state/index.md
        - Meta Hardware Programming: user-guide/meta/index.md
    - About:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/LICENSE.md
        - Acknowledgements: about/acknowledgements.md

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
markdown_extensions:
    - pymdownx.arithmatex

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2019 <a href="https://www.researchgate.net/profile/Oron_Port">Oron Port</a> and <a href="https://yoav.net.technion.ac.il">Yoav Etsion</a>

plugins:
    - search
