# Project information
site_name: DFDocs
site_url: https://dfianthdl.github.io/
site_description: DFiant Hardware Description Language (HDL) Documentation
site_author: Oron Port

# Repository
repo_name: 'DFiantHDL/DFiant'
repo_url: 'https://github.com/DFiantHDL/DFiant'

# Copyright
copyright: Copyright &copy; 2019 <a href="https://www.researchgate.net/profile/Oron_Port">Oron Port</a> and <a href="https://yoav.net.technion.ac.il">Yoav Etsion</a>

# Configuration
theme:
    name: 'material'
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'    
    feature:
        tabs: true
    logo:
        icon: 'home'    
        
# Customization
extra:
  social:
    - type: 'github'
      link: 'https://www.github.com/soronpo/'
    - type: 'researchgate'
      link: 'https://www.researchgate.net/profile/Oron_Port'
    - type: 'twitter'
      link: 'https://twitter.com/soronpo'
        

nav:
    - Introduction: 
        - 'DFiant: First Look': intro/first-look/index.md
        - Motivation (Why Another HDL): intro/motivation/index.md
        - A Dataflow Hardware Description Abstraction: intro/dataflow-abstraction/index.md
    - Getting Started:
        - Initial Setup: getting-started/initial-setup/index.md
        - Hello Hardware World: getting-started/hello-world.md
    - User Guide:
        - Type System: user-guide/type-system/index.md
        - Connectivity: user-guide/connectivity/index.md
        - 'State & Memory': user-guide/state/index.md
        - Meta Hardware Programming: user-guide/meta/index.md
        - Simulation: user-guide/simulation/index.md
        - Synthesis: user-guide/synthesis/index.md
    - About:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/LICENSE.md
        - Acknowledgements: about/acknowledgements.md

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.arithmatex
    - pymdownx.superfences
    - codehilite:
        guess_lang: false
        linenums: true
        
extra_css:
    - css/vs.css
    # - css/extra.css


plugins:
    - search
