name: DFDocs

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'docs/**'
      - 'docs_overrides/**'
      - 'mkdocs.yml'
      - '.github/workflows/dfdocs.yml'
      - 'lib/src/test/scala/docExamples/**'
      - 'lib/src/test/resources/ref/**'
  pull_request:
    branches: 
      - main
      - dev
    paths:
      - 'docs/**'
      - 'docs_overrides/**'
      - 'mkdocs.yml'
      - '.github/workflows/dfdocs.yml'
      - 'lib/src/test/scala/docExamples/**'
      - 'lib/src/test/resources/ref/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x' 
      - name: Build
        run: |
          python -m pip install --upgrade pip 
          pip install -r docs/requirements.txt
          curl -fsSL https://d2lang.com/install.sh | sh
          npm install d3-hwschematic --save
          mkdocs build --verbose --clean #--strict
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DFDOCS_TOKEN }}
          repository-name: DFiantHDL/DFiantHDL.github.io
          branch: master
          folder: site 
          clean: true # Automatically remove deleted files from the deploy branch