name: DFDocs

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x' 
      - name: Build
        run: |
          python -m pip install --upgrade pip 
          pip install pygments
          pip install mkdocs
          pip install mkdocs-material
          pip install pymdown-extensions
          pip install mkdocs-redirects
          pip install mkdocs-glightbox
          pip install mkdocs-autorefs
          mkdocs build --verbose --clean #--strict
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.DFDOCS_TOKEN }}
          REPOSITORY_NAME: DFiantHDL/DFiantHDL.github.io
          BRANCH: master
          FOLDER: site 
          CLEAN: true # Automatically remove deleted files from the deploy branch