name: Release
on:
  push:
    branches: [main, milestone]
    tags: ["*"]
    paths-ignore:
      - 'docs/**'
      - 'docs_overrides/**'
      - 'mkdocs.yml'  
      - '.github/workflows/dfdocs.yml'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
        with:
          jvm: terumin:1.17
          apps: sbt bloop
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
